# travis-ci.org build & test configuration
language: python

python:
  - "2.7"
  #- "3.2"

env:
  matrix:
    - ROOT=5-34-18
    - ROOT=6-00-00

install: source ci/install.sh

script:

  # Check if root and PyROOT work ok
  - time root -l -q
  - time python -c 'import ROOT; ROOT.TBrowser()'

  # Check that RooUnfold can be imported
  - time python -c 'from ROOT import gSystem; gSystem.Load("libRooUnfold.so");from ROOT import RooUnfoldResponse'

  # https://github.com/rootpy/rootpy/pull/176#issuecomment-13712313
  - ls -la /dev/shm
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  #- sudo chmod a+w /dev/shm
  - ls -la /dev/shm
